"""empty message

Revision ID: fc34d8807f34
Revises: 6131cb10a9f7
Create Date: 2019-10-23 15:03:44.315648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc34d8807f34'
down_revision = '6131cb10a9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=280), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dica_description'), 'dica', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dica_description'), table_name='dica')
    op.drop_table('dica')
    # ### end Alembic commands ###
